title: "Educents"
description: "SEO starter with Minimal Mistakes"

# --- IMPORTANTE ---
# Para que funcione en GitHub Pages en este repo:
url: "https://blinkx-original.github.io"
baseurl: "/Jekyll-With-Minimal-Mistakes"
# Cuando uses tu dominio propio (ej: educents.com), cambiá a:
# url: "https://educents.com"
# baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins compatibles con GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Minimal Mistakes skin (color theme): air, default, dark, neon, sunrise, etc.
minimal_mistakes_skin: "air"

# Search (Lunr)
search: true

# Permalink structure
permalink: /:categories/:title/

# Excludes (won't be published)
exclude:
  - README.md
  - node_modules
  - vendor

