# =========================
#  Minimal Mistakes · Jekyll
#  Config para GitHub Pages (Project Page)
# =========================

title: "Tu Sitio"
description: "Descripción del sitio"
locale: "es-ES"

# Project Page de GitHub Pages
url: "https://blinkx-original.github.io"         # tu dominio de usuario
baseurl: "/Jekyll-With-Minimal-Mistakes"         # nombre exacto del repo, con "/"

# Tema (usar remote_theme, NO 'theme:')
remote_theme: "mmistakes/minimal-mistakes"        # también puedes fijar versión: @4.26.2
minimal_mistakes_skin: "default"

timezone: "Europe/Berlin"
future: true

# Plugins permitidos por GitHub Pages
plugins:
  - jekyll-remote-theme      # necesario para remote_theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Navegación (ejemplo)
# navigation:
#   - title: "Home"
#     url: /
#   - title: "Blogs"
#     url: /blogs/
#   - title: "Products"
#     url: /products/
#   - title: "Search"
#     url: /search/

permalink: /:categories/:title/

# Paginación del blog (nuestro índice está en /blogs/)
paginate: 1
paginate_path: "/blogs/page:num/"

# UI
breadcrumbs: true
share: true

# Comentarios (pendiente completar IDs si activas)
comments:
  provider: ""   # "giscus" o "disqus" cuando lo actives
  giscus:
    repo: ""
    repo_id: ""
    category: ""
    category_id: ""
    mapping: "pathname"
    reactions_enabled: "1"
  disqus:
    shortname: ""

# Autor por defecto
author: martin

# Defaults para POSTS
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar: false
      header:
        overlay: false
      cla
