# --- Sitio (básico) ---
title: "Tu Sitio"
description: "Descripción del sitio"
locale: "es-ES"
url: "https://tu-dominio.com"     # ← cambia
baseurl: ""                       # ← si publicas en subcarpeta, ponla (ej: /blog)

theme: minimal-mistakes-jekyll

# --- Navegación principal (opcional, ejemplo) ---
# navigation:
#   - title: "Blog"
#     url: /blog/
#   - title: "Categorías"
#     url: /categories/

# --- Plugins permitidos por GitHub Pages ---
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# --- Paginación del blog ---
paginate: 1
paginate_path: "/blog/page:num/"

# --- Breadcrumbs ---
breadcrumbs: true

# --- Compartir ---
share: true

# --- Comentarios (lo dejamos listo; completamos IDs luego) ---
comments:
  provider: ""   # "giscus" o "disqus" cuando lo habilitemos
  giscus:
    repo: ""         # ← completar luego
    repo_id: ""
    category: ""
    category_id: ""
    mapping: "pathname"
    reactions_enabled: "1"
  disqus:
    shortname: ""    # ← completar si usas Disqus

# --- Autor por defecto (ver _data/authors.yml) ---
author: martin

# --- Permalinks (opcional, simple) ---
permalink: /:categories/:title/

# --- Defaults para POSTS (aplica a todo el blog) ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar: false
      header:
        overlay: false
      classes: ""               # normal (no 'wide')
      author_profile: true      # muestra caja de autor debajo del post
      show_date: false          # ocultar fecha
      read_time: false          # ocultar tiempo de lectura
      show_tags: false          # ocultar tags
      related: false            # desactivar related posts
      comments: true            # (se verán cuando configuremos provider)
      share: true               # botones de compartir
      breadcrumbs: true
      teaser:                   # sin teaser => evita miniaturas automáticas en el listado

# --- Sass / includes (para poder cargar CSS custom) ---
sass:
  style: compressed

include:
  - assets/css
  - _pages
