# =========================
# Minimal Mistakes · GitHub Pages (Project Page)
# =========================

title: "Tu Sitio"
description: "Descripción del sitio"
locale: "es-ES"

# URL de usuario/org + baseurl = nombre EXACTO del repo
url: "https://blinkx-original.github.io"
baseurl: "/Jekyll-With-Minimal-Mistakes"

# Usa remote_theme (no 'theme:')
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"

timezone: "Europe/Berlin"
future: true

# Plugins soportados por GH Pages
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Enlaces
permalink: /:categories/:title/

# Paginación (nuestro índice vive en /blogs/)
paginate: 1
paginate_path: "/blogs/page:num/"

# UI
breadcrumbs: true
share: true

# Comentarios (lo activas luego)
comments:
  provider: ""         # "giscus" o "disqus" cuando lo actives
  giscus:
    repo: ""
    repo_id: ""
    category: ""
    category_id: ""
    mapping: "pathname"
    reactions_enabled: "1"
  disqus:
    shortname: ""

# Autor por defecto (define 'martin' en _data/authors.yml)
author: martin

# Defaults para posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar: false
      header:
        overlay: false
      classes: ""               # normal (no 'wide')
      author_profile: true
      show_date: false
      read_time: false
      show_tags: false
      related: false
      comments: true
      share: true
      breadcrumbs: true
      teaser: null              # usa null explícito

# CSS propio
sass:
  style: compressed

include:
  - assets/css
  - _pages

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
